service: my-express-app

provider:
  name: aws
  runtime: nodejs20.x
  environment:
    STRIPE_SECRET_KEY: ${env:STRIPE_SECRET_KEY, 'test'}
    SHIPPO_TOKEN: ${env:SHIPPO_TOKEN, 'test'}
    WAREHOUSE_NAME: ${env:WAREHOUSE_NAME, 'Dissonant'}
    WAREHOUSE_STREET: ${env:WAREHOUSE_STREET, '789 9th St APT 4C'}
    WAREHOUSE_CITY: ${env:WAREHOUSE_CITY, 'New York'}
    WAREHOUSE_STATE: ${env:WAREHOUSE_STATE, 'NY'}
    WAREHOUSE_ZIP: ${env:WAREHOUSE_ZIP, '10019'}
    WAREHOUSE_COUNTRY: ${env:WAREHOUSE_COUNTRY, 'US'}
    EMAIL_USER: ${env:EMAIL_USER, 'no-reply@dissonanthq.com'}
    WAREHOUSE_EMAIL: ${env:WAREHOUSE_EMAIL, 'dissonant.helpdesk@gmail.com'}
    FIREBASE_PROJECT_ID: ${env:FIREBASE_PROJECT_ID, 'dissonantapp2'}
    SENDGRID_API_KEY: ${env:SENDGRID_API_KEY, ''}

functions:
  app:
    handler: index.handler
    timeout: 30
    events:
      - http:
          path: create-payment-intent
          method: post
          cors: true
      - http:
          path: validate-address
          method: post
          cors: true
      - http:
          path: create-paypal-payment
          method: post
          cors: true
      - http:
          path: create-shipping-labels
          method: post
          cors: true
      - http:
          path: shippo-webhook
          method: post
          cors: true
      - http:
          path: check-order-status
          method: post
          cors: true
      - http:
          path: test-email
          method: post
          cors: true
      - http:
          path: test-shipping-emails
          method: post
          cors: true
      - http:
          path: test-webhook
          method: post
          cors: true